stages:
  - build
  - test
  - deploy

setup:
  stage: test
  script:
    - echo %PYTHON%
    - CALL %PYTHON% suite_Cura/startup.py
  tags:
    - windows

execute-tests:
  stage: test
  script:
    - echo %SQUISH_DIR%
    - echo "Starting squishserver"
    - START %SQUISH_DIR%/bin/squishserver
    - echo "Starting tests..."
    - CALL %SQUISH_DIR%/bin/squishrunner --testsuite suite_Cura --testcase tst_Performance_Booting --reportgen html,reports --reportgen stdout
    - ping 127.0.0.1 -n 6 > nul
  after_script:
    - echo "Stopping squishserver..."
    - CALL %SQUISH_DIR%/bin/squishserver --stop &
  artifacts:
    paths:
      - reports/
      - suite_Cura/shared/scripts/Performance.txt
  tags:
    - windows

pages:
  stage: deploy
  dependencies:
    - execute-tests
  script:
    - mv reports/ public/
  artifacts:
    paths:
      - public