setup:
  stage: build
  script:
    - py suite_Cura/startup.py

execute-tests:
  stage: test
  script:
    - echo %SQUISH_DIR%
    - echo "Starting squishserver"
    - START %SQUISH_DIR%/bin/squishserver
    - CALL %SQUISH_DIR%/bin/squishrunner --testsuite suite_Cura --reportgen html,reports --reportgen stdout
    - ping 127.0.0.1 -n 6 > nul
    - echo "Stopping squishserver"
    - CALL %SQUISH_DIR%/bin/squishserver --stop &
  artifacts:
    paths:
      - reports/
  tags:
    - windows

pages:
  stage: deploy
  dependencies:
    - execute-tests
  script:
    - mv reports/ public/
  artifacts:
    paths:
      - public
  only:
    - master