stages:
  - build
  - test

set-env-var:
  stage: build
  script:
  - setx SQUISH_LICENSEKEY_DIR %USERPROFILE%
  tags:
    - windows

execute-tests:
  stage: test
  script:
    - test.bat
  tags:
    - windows